org.gradle.jvmargs=-Xmx8G

minecraft_version=26.1

archives_base_name=colorize
mod_version=1.13.0
maven_group=pl.panszelescik.colorize

fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1

//forge_version=1.21.11-61.0.2

//neoforge_version=21.11.6-beta

//jei_minecraft_version=1.21.11
//jei_version=27.0.0.1
