org.gradle.jvmargs=-Xmx8G

minecraft_version=1.21.9
//enabled_platforms=fabric,forge,neoforge,quilt
enabled_platforms=fabric,forge,neoforge

archives_base_name=colorize
mod_version=1.12.5
maven_group=pl.panszelescik.colorize

//architectury_version=9.1.12

fabric_loader_version=0.17.2
fabric_api_version=0.133.14+1.21.9

forge_version=1.21.8-58.1.6

neoforge_version=21.8.47

#quilt_loader_version=0.26.3
#quilt_fabric_api_version=11.0.0-alpha.3+0.102.0-1.21

jei_minecraft_version=1.21.8
jei_version=24.2.0.6

loom.allowMismatchedPlatformVersion = true
