// TODO: Forge dla Minecraft 26.1 nie jest jeszcze dostępny.
// Gdy Forge zostanie wydany, skonfigurować ten moduł z ForgeGradle:
//
// plugins {
//     id "net.minecraftforge.gradle"
// }
//
// dependencies {
//     forge "net.minecraftforge:forge:${rootProject.forge_version}"
//     implementation project(":common")
// }
