// TODO: NeoForge dla Minecraft 26.1 nie jest jeszcze dostępny.
// Gdy NeoForge zostanie wydany, skonfigurować ten moduł z ModDevGradle:
//
// plugins {
//     id "net.neoforged.moddev"
// }
//
// neoForge {
//     version = rootProject.neoforge_version
// }
//
// dependencies {
//     implementation project(":common")
// }
