plugins {
    id "net.fabricmc.fabric-loom"
}

repositories {
    maven { url "https://modmaven.dev" }
}

// JEI - wyłączone do czasu wydania wersji dla 26.1
sourceSets.main.java.exclude "**/jei/**"

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    compileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    //api "mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}"
}

